---------------------------------------TYPE_OF_LIBRARY_CARD(借书证类型表)---------------------------
--重建表TYPE_OF_LIBRARY_CARD
DROP table TYPE_OF_LIBRARY_CARD CASCADE CONSTRAINTS PURGE;
CREATE TABLE "SYSTEM"."TYPE_OF_LIBRARY_CARD" 
   (
    "TNO" NUMBER NOT NULL, 
	"TNAME" VARCHAR2(20 BYTE) NOT NULL, 
	"TMAX" NUMBER NOT NULL, 
	"TLONG" NUMBER NOT NULL,
    PRIMARY KEY (TNO)
   );
--建立唯一约束
ALTER TABLE TYPE_OF_LIBRARY_CARD ADD CONSTRAINT TYPE_OF_LIBRARY_CARD_UK1 UNIQUE ("TNAME") ENABLE;
--增加自增序列
drop sequence TYPE_OF_LIBRARY_CARD_tb_seq;    
create sequence TYPE_OF_LIBRARY_CARD_tb_seq minvalue 1 maxvalue 99999999    
         increment by 1    
         start with 1;
--创建自增触发器
create or replace trigger TYPE_OF_LIBRARY_CARD_tb_tri      
before insert on TYPE_OF_LIBRARY_CARD
 for each row  
begin
select TYPE_OF_LIBRARY_CARD_tb_seq.nextval into :new.TNO from dual;
end;    
--增加注释
   COMMENT ON COLUMN "SYSTEM"."TYPE_OF_LIBRARY_CARD"."TNO" IS '借书证类型编号(可自增)';
 
   COMMENT ON COLUMN "SYSTEM"."TYPE_OF_LIBRARY_CARD"."TNAME" IS '类型名字(唯一约束)';
 
   COMMENT ON COLUMN "SYSTEM"."TYPE_OF_LIBRARY_CARD"."TMAX" IS '最大借阅数(本)';
 
   COMMENT ON COLUMN "SYSTEM"."TYPE_OF_LIBRARY_CARD"."TLONG" IS '最大借阅时间(天)';
--插入数据
INSERT INTO "SYSTEM"."TYPE_OF_LIBRARY_CARD" (TNAME, TMAX, TLONG) VALUES ('本科生借书证',5,60);
INSERT INTO "SYSTEM"."TYPE_OF_LIBRARY_CARD" (TNAME, TMAX, TLONG) VALUES ('研究生借书证',10,30);
INSERT INTO "SYSTEM"."TYPE_OF_LIBRARY_CARD" (TNAME, TMAX, TLONG) VALUES ('教师借书证',5,60);
INSERT INTO "SYSTEM"."TYPE_OF_LIBRARY_CARD" (TNAME, TMAX, TLONG) VALUES ('领导借书证',10,60);
INSERT INTO "SYSTEM"."TYPE_OF_LIBRARY_CARD" (TNAME, TMAX, TLONG) VALUES ('临时借书证',2,7);





---------------------------------------library_card(借书证表)---------------------------
--重建表LIBRARY_CARD
DROP table "SYSTEM"."LIBRARY_CARD" CASCADE CONSTRAINTS PURGE;
CREATE TABLE "SYSTEM"."LIBRARY_CARD" 
   (
    "CNO" VARCHAR2(12 BYTE) NOT NULL, 
   	"CAN" VARCHAR2(32 BYTE) NOT NULL,
	"CNAME" VARCHAR2(10 BYTE) NOT NULL,
	"CSEX" VARCHAR2(2 BYTE) NOT NULL,
	"TNO" NUMBER NOT NULL, 
	"CSTATUS" NUMBER(1,0) NOT NULL,
	"CPSW" VARCHAR2(32 BYTE) NOT NULL,
    PRIMARY KEY (CNO),
CONSTRAINT "LIBRARY_CARD_TYPE_OF_LIBR_FK1" FOREIGN KEY ("TNO")
	  REFERENCES "SYSTEM"."TYPE_OF_LIBRARY_CARD" ("TNO") ENABLE
   );
--建立唯一约束
ALTER TABLE LIBRARY_CARD ADD CONSTRAINT LIBRARY_CARD_UK1 UNIQUE ("CAN") ENABLE;
--增加注释
   COMMENT ON COLUMN "SYSTEM"."LIBRARY_CARD"."CNO" IS '借书证ID';
 
   COMMENT ON COLUMN "SYSTEM"."LIBRARY_CARD"."CNAME" IS '用户名字';
 
   COMMENT ON COLUMN "SYSTEM"."LIBRARY_CARD"."CSEX" IS '性别';
 
   COMMENT ON COLUMN "SYSTEM"."LIBRARY_CARD"."TNO" IS '借书证类型(外键)';
 
   COMMENT ON COLUMN "SYSTEM"."LIBRARY_CARD"."CSTATUS" IS '状态1激活,0禁用';
 
   COMMENT ON COLUMN "SYSTEM"."LIBRARY_CARD"."CPSW" IS '用户密码';
--插入数据
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('201500406103', '黄俊杰','男','1', '1', 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('201500406096', '小韦','女','1', '1', 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001001', '刘华','男','2', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('0000001', '秦屿','男','4', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001002', '林晨钰','女','2', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001003', '祝雨柏','女','1', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001004', '世靖之','男','1', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001005', '东雅诗','女','3', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001006', '宁玲珑','女','3', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001007', '温寒烟','女','5', 1, 'e10adc3949ba59abbe56e057f20f883e');



---------------------------------借书证管理视图(vm_CardAndType)---------------------------
CREATE VIEW VW_CARDANDTYPE AS SELECT l.CNO,l.CAN,l.CPSW,l.CNAME,l.CSEX,l.CSTATUS,t.TNAME FROM library_card l,TYPE_OF_LIBRARY_CARD t where l.TNO=t.TNO ORDER BY l.CNO;



---------------------------------------管理员表(manage)  -----------------------------
--重建表MANAGE
DROP table "SYSTEM"."MANAGE" CASCADE CONSTRAINTS PURGE;
CREATE TABLE "SYSTEM"."MANAGE" 
   (
    "MNO" NUMBER NOT NULL, 
	"MNAME" VARCHAR2(32 BYTE) NOT NULL,
	"MPSW" VARCHAR2(32 BYTE) NOT NULL,
	"MREALNAME" VARCHAR2(10 BYTE) NOT NULL,
	"MPOWER" NUMBER(1,0) NOT NULL,
	"CREATETIME" DATE NOT NULL,
	"LOGINTIME" DATE,
    PRIMARY KEY (MNO),
   );
--建立唯一约束
ALTER TABLE MANAGE ADD CONSTRAINT MANAGE_UK1 UNIQUE ("MNAME") ENABLE;

--增加注释
   COMMENT ON COLUMN "MANAGE"."LIBRARY_CARD"."CNO" IS '借书证ID';
 
   COMMENT ON COLUMN "MANAGE"."LIBRARY_CARD"."CNAME" IS '用户名字';
 
   COMMENT ON COLUMN "MANAGE"."LIBRARY_CARD"."CSEX" IS '性别';
 
   COMMENT ON COLUMN "MANAGE"."LIBRARY_CARD"."TNO" IS '借书证类型(外键)';
 
   COMMENT ON COLUMN "MANAGE"."LIBRARY_CARD"."CSTATUS" IS '状态1激活,0禁用';
 
   COMMENT ON COLUMN "SYSTEM"."LIBRARY_CARD"."CPSW" IS '用户密码';
--插入数据
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('201500406103', '黄俊杰','男','1', '1', 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('201500406096', '小韦','女','1', '1', 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001001', '刘华','男','2', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('0000001', '秦屿','男','4', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001002', '林晨钰','女','2', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001003', '祝雨柏','女','1', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001004', '世靖之','男','1', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001005', '东雅诗','女','3', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001006', '宁玲珑','女','3', 1, 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO "SYSTEM"."LIBRARY_CARD" (CNO, CNAME,CSEX, TNO, CSTATUS, CPSW) VALUES ('1001007', '温寒烟','女','5', 1, 'e10adc3949ba59abbe56e057f20f883e');


---------------------------------------图书室表(Library) ---------------------------
--唯一约束
ALTER TABLE Library ADD CONSTRAINT Library_UK1 UNIQUE ("LPOSITION") ENABLE;
自然科学室
人文科学室


---------------------------------------图书室视图(vw_roominfo)----------------------------
CREATE VIEW VW_ROOMINFO AS SELECT a."LNO",a."LIMG",a."LNAME",a."LPOSITION",a."MNO",b.MREALNAME
    
FROM LIBRARY a left join MANAGE b on (a.MNO=b.MNO);
---------------------------------------书本表(books)--------------------------------------
约束 isbn
库存量大于0
---------------------------------------图书视图-(vw_bookinfo)--------------------------------------------
CREATE VIEW VW_BOOKINFO AS SELECT a.*,b.lposition,b.lname
    
FROM books a,LIBRARY b where a.lno=b.lno;