
  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VW_ROOMINFO" ("LNO", "LIMG", "LNAME", "LPOSITION", "MNO", "MREALNAME") AS 
  SELECT a."LNO",a."LIMG",a."LNAME",a."LPOSITION",a."MNO",b.MREALNAME
    
FROM LIBRARY a left join MANAGE b on (a.MNO=b.MNO);
 

  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VW_CARDANDTYPE" ("CNO", "CNAME", "CSEX", "TNO", "CSTATUS", "CPSW", "CAN", "CARREARS", "TNAME") AS 
  SELECT l."CNO",l."CNAME",l."CSEX",l."TNO",l."CSTATUS",l."CPSW",l."CAN",l."CARREARS",t.TNAME FROM library_card l,TYPE_OF_LIBRARY_CARD t where l.TNO=t.TNO ORDER BY l.CNO;
 

  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VW_BOOKINFO" ("BNO", "BAUTHOR", "BCOPY", "BIMG", "BINVENTORY", "BISBN", "BNAME", "BPRESS", "BPRICE", "LNO", "LPOSITION", "LNAME") AS 
  SELECT a."BNO",a."BAUTHOR",a."BCOPY",a."BIMG",a."BINVENTORY",a."BISBN",a."BNAME",a."BPRESS",a."BPRICE",a."LNO",b.lposition,b.lname
    
FROM books a left join LIBRARY b on (a.lno=b.lno);
 
